version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
     - checkout
     - run: env
     - run: pwd
     - run: sudo bash .circleci/install-requirements.sh
     - run: sleep 30m
